theme: jekyll-theme-minimal
title: "Final-Year Electrical Engineering Student at KMUTT ,Nutchapol Aueachittrakul"
description: "interested in Renewable Energy especially Solar Energy, PV Systems, Power Electronics and Machine Learning."
