theme: jekyll-theme-minimal
title: "Electrical Engineering ,Nutchapol Aueachittrakul"
description: "Student in Electrical Engineering  interested in Solar Energy, PV Systems, Power Electronics and Machine Learning."
